<a href="https://colab.research.google.com/github/UnnatiChitra/Linear-Regression/blob/main/Batch_Gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df= pd.read_csv('economic_index.csv')
df = df.iloc[:,1:]
df.head()

year  month  interest_rate  unemployment_rate  index_price
0  2017     12           2.75                5.3         1464
1  2017     11           2.50                5.3         1394
2  2017     10           2.50                5.3         1357
3  2017      9           2.50                5.3         1293
4  2017      8           2.50                5.4         1256

In [3]:
df.shape

(24, 5)

In [12]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()

In [14]:
df_scaled = sc.fit_transform(df)

# Keep original column names by creating a DataFrame from the scaled numpy array
df_scaled = pd.DataFrame(df_scaled, columns=df.columns)
df_scaled.head()

year     month  interest_rate  unemployment_rate  index_price
0   1.0  1.593255       1.978803          -1.470264     1.909452
1   1.0  1.303572       1.248168          -1.470264     1.570137
2   1.0  1.013890       1.248168          -1.470264     1.390785
3   1.0  0.724207       1.248168          -1.470264     1.080555
4   1.0  0.434524       1.248168          -1.160735     0.901203

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [16]:
X= df_scaled.iloc[:,:-1].values
y=df_scaled.iloc[:,-1].values
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [17]:
lr=LinearRegression()

In [18]:
lr.fit(X_train,y_train)

LinearRegression()

In [45]:
y_pred = lr.predict(X_test)

array([ 0.52541468, -0.67907578,  1.56634012, -0.94595124,  0.15710648])

In [19]:
lr.intercept_

np.float64(-0.014923247618975191)

In [20]:
lr.coef_

array([0.87866555, 0.4477118 , 0.01255336, 0.02418741])

In [44]:
from sklearn.metrics import r2_score
print('R2_Score:',r2_score(y_test,y_pred) )

R2_Score: 0.9603215002555883


In [21]:
X_train.shape

(19, 4)

In [100]:
X_test.shape

(5, 4)

In [78]:
class BGD:
  def __init__(self, learning_rate=0.01, epoch=100):
    self.intercept_=None
    self.coef_=None
    self.lr= learning_rate
    self.epoch=epoch

  def fit(self, X_train, y_train):
    self.intercept_=0
    self.coef_= np.ones(X_train.shape[1])

    for i in range(self.epoch):
      y_hat= self.intercept_ + np.dot(X_train, self.coef_)

      intercept_=-2*np.mean(y_train-y_hat)
      self.intercept_=self.intercept_- (self.lr*intercept_)

      coef_=-2*np.dot((y_train - y_hat),X_train)/X_train.shape[0]
      self.coef_=self.coef_- (self.lr*coef_)

    print(self.intercept_, self.coef_)

  def predict(self, X_test):
    return self.intercept_ + np.dot(X_test, self.coef_)


In [114]:
reg= BGD(learning_rate=0.1, epoch=10000)

In [115]:
reg.fit(X_train,y_train)

-0.014923247618974844 [0.87866555 0.4477118  0.01255336 0.02418741]


In [116]:
reg.predict(X_test)

array([ 0.52541468, -0.67907578,  1.56634012, -0.94595124,  0.15710648])

In [101]:
y_test

array([ 0.43101015, -0.48029154,  1.90945173, -0.90201094,  0.0238328 ])