In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('economic_index.csv')
df=df.iloc[:,1:]
df.head()

year  month  interest_rate  unemployment_rate  index_price
0  2017     12           2.75                5.3         1464
1  2017     11           2.50                5.3         1394
2  2017     10           2.50                5.3         1357
3  2017      9           2.50                5.3         1293
4  2017      8           2.50                5.4         1256

In [3]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [4]:
df_scaled=sc.fit_transform(df)
df_scaled=pd.DataFrame(df_scaled,columns=df.columns)
df_scaled.head()

year     month  interest_rate  unemployment_rate  index_price
0   1.0  1.593255       1.978803          -1.470264     1.909452
1   1.0  1.303572       1.248168          -1.470264     1.570137
2   1.0  1.013890       1.248168          -1.470264     1.390785
3   1.0  0.724207       1.248168          -1.470264     1.080555
4   1.0  0.434524       1.248168          -1.160735     0.901203

In [5]:
X=df_scaled.iloc[:,:-1].values
y=df_scaled.iloc[:,-1].values

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2, random_state=42)

In [7]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()

In [8]:
lr.fit(X_train, y_train)

LinearRegression()

In [9]:
lr.predict(X_test)

array([ 0.52541468, -0.67907578,  1.56634012, -0.94595124,  0.15710648])

In [10]:
lr.intercept_

np.float64(-0.014923247618975191)

In [11]:
lr.coef_

array([0.87866555, 0.4477118 , 0.01255336, 0.02418741])

In [15]:
import random

In [24]:
class MBGD:
  def __init__(self, batch_size, learning_rate=0.1, epochs=100):
    self.intercept_=None
    self.coef_=None
    self.batch_size= batch_size
    self.lr=learning_rate
    self.epochs=epochs

  def fit(self, X_train , y_train):
    self.intercept_=0
    self.coef_=np.ones(X_train.shape[1])

    for i in range(self.epochs):
      for j in range(int(X_train.shape[0]/self.batch_size)):
        idx = random.sample(range(X_train.shape[0]),self.batch_size)

        y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_

        intercept_der = -2 * np.mean(y_train[idx] - y_hat)
        self.intercept_ = self.intercept_ - (self.lr * intercept_der)

        coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
        self.coef_ = self.coef_ - (self.lr * coef_der)

    print(self.intercept_,self.coef_)


  def predict(self, X_test):

    return np.dot(X_test, self.coef_) + self.intercept_

In [36]:
reg= MBGD(batch_size=10, learning_rate=0.01, epochs=10000)

In [37]:
reg.fit(X_train, y_train)

-0.013824451096556271 [0.86530694 0.45472384 0.0210351  0.01261921]


In [38]:
reg.predict(X_test)

array([ 0.5223132 , -0.68479396,  1.59904427, -0.95215126,  0.12739135])